### ISSUE TITLE
Add basic usage examples

### ISSUE THREAD

**Issue by anapaulagomes** [model-bakers/farm-app#4]
The examples should cover at least the ones in [our docs](https://model-bakery.readthedocs.io/en/latest/basic_usage.html):

- [x] Persistent objects (`make`) #3
- [x] Non persistent objects (`prepare`) #3
- [x] Explicit values for fields #3
- [x] ForeignKeys #3
- [x] OneToOneFields #11
- [x] More than one instance (`_quantity`) #11
- [x] Fill optional  #11
- [x] M2M Relationships #13
- [x] Creating Files #14
- [x] Custom field with field lookups  #11
